# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'spider.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1221, 800)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 31, 132, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.aboutthread = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.aboutthread.setContentsMargins(0, 0, 0, 0)
        self.aboutthread.setObjectName("aboutthread")
        self.threadnum = QtWidgets.QLabel(self.layoutWidget)
        self.threadnum.setObjectName("threadnum")
        self.aboutthread.addWidget(self.threadnum)
        self.threadnumber = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.threadnumber.setFont(font)
        self.threadnumber.setObjectName("threadnumber")
        self.aboutthread.addWidget(self.threadnumber)
        self.runspider = QtWidgets.QPushButton(Form)
        self.runspider.setGeometry(QtCore.QRect(770, 32, 93, 28))
        self.runspider.setDefault(True)
        self.runspider.setObjectName("runspider")
        self.layoutWidget1 = QtWidgets.QWidget(Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(21, 31, 221, 30))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.aboutshop = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.aboutshop.setContentsMargins(0, 0, 0, 0)
        self.aboutshop.setObjectName("aboutshop")
        self.shopname = QtWidgets.QLabel(self.layoutWidget1)
        self.shopname.setObjectName("shopname")
        self.aboutshop.addWidget(self.shopname)
        self.inputshopname = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inputshopname.setFont(font)
        self.inputshopname.setObjectName("inputshopname")
        self.aboutshop.addWidget(self.inputshopname)
        self.datatable = QtWidgets.QTableWidget(Form)
        self.datatable.setGeometry(QtCore.QRect(20, 110, 1181, 681))
        self.datatable.setObjectName("datatable")
        self.datatable.setColumnCount(13)
        self.datatable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.datatable.setHorizontalHeaderItem(12, item)
        self.shopdata = QtWidgets.QLabel(Form)
        self.shopdata.setGeometry(QtCore.QRect(480, 70, 150, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.shopdata.setFont(font)
        self.shopdata.setObjectName("shopdata")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(410, 30, 180, 30))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.aboutpage = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.aboutpage.setContentsMargins(0, 0, 0, 0)
        self.aboutpage.setObjectName("aboutpage")
        self.pagebutton = QtWidgets.QPushButton(self.layoutWidget_2)
        self.pagebutton.setDefault(True)
        self.pagebutton.setObjectName("pagebutton")
        self.aboutpage.addWidget(self.pagebutton)
        self.pagecount = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pagecount.setFont(font)
        self.pagecount.setText("")
        self.pagecount.setObjectName("pagecount")
        self.aboutpage.addWidget(self.pagecount)
        self.layoutWidget_3 = QtWidgets.QWidget(Form)
        self.layoutWidget_3.setGeometry(QtCore.QRect(600, 30, 162, 30))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.aboutspiderpage = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.aboutspiderpage.setContentsMargins(0, 0, 0, 0)
        self.aboutspiderpage.setObjectName("aboutspiderpage")
        self.spiderpage = QtWidgets.QLabel(self.layoutWidget_3)
        self.spiderpage.setObjectName("spiderpage")
        self.aboutspiderpage.addWidget(self.spiderpage)
        self.pagenumber = QtWidgets.QLineEdit(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pagenumber.setFont(font)
        self.pagenumber.setObjectName("pagenumber")
        self.aboutspiderpage.addWidget(self.pagenumber)
        self.layoutWidget_4 = QtWidgets.QWidget(Form)
        self.layoutWidget_4.setGeometry(QtCore.QRect(870, 30, 331, 30))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.queryscope = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.queryscope.setContentsMargins(0, 0, 0, 0)
        self.queryscope.setObjectName("queryscope")
        self.scope = QtWidgets.QLabel(self.layoutWidget_4)
        self.scope.setObjectName("scope")
        self.queryscope.addWidget(self.scope)
        self.scope1 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scope1.setFont(font)
        self.scope1.setObjectName("scope1")
        self.queryscope.addWidget(self.scope1)
        self.scope3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.scope3.setObjectName("scope3")
        self.queryscope.addWidget(self.scope3)
        self.scope2 = QtWidgets.QLineEdit(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.scope2.setFont(font)
        self.scope2.setObjectName("scope2")
        self.queryscope.addWidget(self.scope2)
        self.finddatafromsql = QtWidgets.QPushButton(self.layoutWidget_4)
        self.finddatafromsql.setDefault(True)
        self.finddatafromsql.setObjectName("finddatafromsql")
        self.queryscope.addWidget(self.finddatafromsql)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "京东商品信息爬虫"))
        self.threadnum.setText(_translate("Form", "线程数量："))
        self.runspider.setText(_translate("Form", "开始爬虫"))
        self.shopname.setText(_translate("Form", "商品名称："))
        item = self.datatable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "获取时间"))
        item = self.datatable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "商品ID"))
        item = self.datatable.horizontalHeaderItem(2)
        item.setText(_translate("Form", "商品名称"))
        item = self.datatable.horizontalHeaderItem(3)
        item.setText(_translate("Form", "店铺名称"))
        item = self.datatable.horizontalHeaderItem(4)
        item.setText(_translate("Form", "详情链接"))
        item = self.datatable.horizontalHeaderItem(5)
        item.setText(_translate("Form", "品牌"))
        item = self.datatable.horizontalHeaderItem(6)
        item.setText(_translate("Form", "价格"))
        item = self.datatable.horizontalHeaderItem(7)
        item.setText(_translate("Form", "评论总数"))
        item = self.datatable.horizontalHeaderItem(8)
        item.setText(_translate("Form", "好评率"))
        item = self.datatable.horizontalHeaderItem(9)
        item.setText(_translate("Form", "差评率"))
        item = self.datatable.horizontalHeaderItem(10)
        item.setText(_translate("Form", "选择颜色"))
        item = self.datatable.horizontalHeaderItem(11)
        item.setText(_translate("Form", "选择大小"))
        item = self.datatable.horizontalHeaderItem(12)
        item.setText(_translate("Form", "效果图片"))
        self.shopdata.setText(_translate("Form", "查询到的数据"))
        self.pagebutton.setText(_translate("Form", "获取商品页数"))
        self.spiderpage.setText(_translate("Form", "输入爬取页数："))
        self.scope.setText(_translate("Form", "查询范围："))
        self.scope3.setText(_translate("Form", "到"))
        self.finddatafromsql.setText(_translate("Form", "查询"))
